### ISSUE TITLE
不知道哪里出问题了

### ISSUE THREAD

**Issue by seymer** [Leask/socratex#11]
不知道哪里出问题了，log:
`E: 40F880BB3E7F0000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 46

E: 40F880BB3E7F0000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 46

E: 40F880BB3E7F0000:error:0A000102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1677:`

我注意到有一个类似的 issue 提出，但似乎并没有真正解决就被关闭了。

**Comment by Leask** [comment]
剛剛升級的版本解決了這個問題，抱歉，因為老婆剛剛生了小女兒二胎，所以，開源這邊時間分配比較少了，抱歉。🤣
