### ISSUE TITLE
"Unexpected reserved word"

### ISSUE THREAD

**Issue by lmpprk** [Leask/socratex#12]
Following the instructions and got this error when trying to start the proxy:

```
file:///root/.npm/_npx/cf6c8ea642fc233a/node_modules/socratex/main.mjs:31
await utilitas.locate(utilitas.__(import.meta.url, 'package.json')); // keep 1st
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by Leask** [comment]
What in your nodejs version? And as I mention, you can not run the program via `npx`.

**Comment by lmpprk** [comment]
Ah it was the nodejs version, my machine turned out to have a very old version (12) and upgrading solved the problem.

Thank you for making this awesome tool!

**Comment by Leask** [comment]
🍻
