### ISSUE TITLE
error，不支持的协议，请问是什么问题。

### ISSUE THREAD

**Issue by U201413497** [Leask/socratex#13]
debian11系统 ,npm 9.8.0
使用没问题。日志存在报错。
安装方式Classic method
以下为报错部分的log
[SOCRATEX 2023-08-25T04:02:02.468Z] (15) ::ffff:89.45.6.117:39294 E: 00B85EB76A7F0000:error:0A0000C1:SSL routines:tls_post_process_client_hello:no shared cipher:../deps/openssl/openssl/ssl/statem/statem_srvr.c:2240:

[SOCRATEX 2023-08-25T04:02:04.522Z] (15) ::ffff:89.45.6.117:39322 E: 00B85EB76A7F0000:error:0A000102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1677:

[SOCRATEX 2023-08-25T04:02:06.554Z] (13) ::ffff:51.81.245.138:42790 E: Proxy Authorization Required
[SOCRATEX 2023-08-25T04:02:07.152Z] (15) ::ffff:51.81.245.138:42796 E: Proxy Authorization Required
[SOCRATEX 2023-08-25T04:02:07.289Z] (13) ::ffff:89.45.6.117:36594 E: read ECONNRESET
[SOCRATEX 2023-08-25T04:02:07.683Z] (13) ::ffff:89.45.6.117:36604 E: 00B85EB76A7F0000:error:0A0000C1:SSL routines:tls_early_post_process_client_hello:no shared cipher:../deps/openssl/openssl/ssl/statem/statem_srvr.c:1762:

[SOCRATEX 2023-08-25T04:02:07.729Z] (13) ::ffff:89.45.6.117:36618 E: 00B85EB76A7F0000:error:0A00006C:SSL routines:tls_parse_ctos_key_share:bad key share:../deps/openssl/openssl/ssl/statem/extensions_srvr.c:646:

**Comment by Leask** [comment]
你好，請問你如何配置到客戶端的？這個錯誤是沒有做完auth就連接了？你應該通過pac文件配置到客戶端。

**Comment by U201413497** [comment]
感谢开发者的回复和辛苦开发，我用的是win11，用的wpad 这个链接，在代理那里设置的，使用没有任何问题，只是看服务器的log有这个报错。所以请教一下。搭建是Classic method:这种方式，断开服务器的ssh后，也就是关闭窗口后好像无法使用，希望可以后台运行。

**Comment by Leask** [comment]
那可能是系統某一些協議不支持，但是瀏覽器正常識別了，這個問題不大，估計就是某一些很生僻的地方在用。這個可以等後來遇到問題再好調試。關於ssh之後運行程序怎麼後台，你可以看看這個文章：https://gnu-linux.readthedocs.io/zh/latest/Chapter06/sshBackstage.html 。
不用客氣，有問題繼續交流，我先把這個issue關了，有其他問題單獨再開新的。
