### ISSUE TITLE
无法代理telegram

### ISSUE THREAD

**Issue by qiangweihewu** [Leask/socratex#7]
你好，谢谢更新！很欣喜得知这个项目，使用非常简便！

目前唯一遇到的问题是无法代理telegram桌面软件的流量，报错如下：
E: 10404FB5FFFF0000:error:0A00009C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:345:
E: 10404FB5FFFF0000:error:0A00009B:SSL routines:ssl3_get_record:https proxy request:../deps/openssl/openssl/ssl/record/ssl3_record.c:349:

我猜测可能是因为telegram使用的是mtproxy加密协议，走tcp流量？

有办法支持吗？

期待解答，谢谢！

**Comment by Leask** [comment]
telegram 不支持 https 代理，僅支持 http 代理，目前沒有比較簡單的方法。原計畫設計這個項目的時候就是盡可能不需要在客戶端運行一個進程，所以才選擇 https 代理這種比較面向未來的方式。但是最近遇到不少例如你這種情況，大家的確需要本地可以起一個客戶端把遠程的 https 代理轉化爲更多軟件可以識別的 http 代理。當然，有很多這樣的第三方工具可以選擇，但是我也在計畫提供一個簡單的版本，請留意後續的更新，謝謝。

**Comment by qiangweihewu** [comment]
非常感谢！
这里想再问一个问题，默认的端口走的是443和80，我在Lib修改或者添加port参数后443可以改，但是80一直无法改，不知道有可能是什么原因造成的，可以如何修改，期待回复，谢谢！

**Comment by Leask** [comment]
提問無響應，目前沒有適當的後續處理，暫時先關閉此issue。
