### ISSUE TITLE
ssl证书无效

### ISSUE THREAD

**Issue by qiangweihewu** [Leask/socratex#8]
报错如下，似乎是没有自签证书还是客户端无法识别自签证书？运行端口是默认的80和443

[SOCRATEX 2023-03-30T20:19:53.963Z] (1) ::ffff:13.215.205.50:33982 E: 00789CEF337F0000:error:0A000416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 46

**Comment by Leask** [comment]
自簽證書對於這個服務來說是沒有意義的，這個服務的原理就是通過SSL證書加密通訊。你需要在牆外一個機器上運行這個服務，並且保證這個服務的80和443端口是可以被訪問的。請再認真研究一下，如果有問題，十分歡迎回來討論，很樂意與你一起解決問題，並進一步完善項目。
