### ISSUE TITLE
failed to set up socratex

### ISSUE THREAD

**Issue by JJYpeak** [Leask/socratex#9]
I tried to deploy socratex following the instructions but got errors as below: 

node:internal/process/esm_loader:100
    internalBinding('errors').triggerUncaughtException(
                              ^

AssertionError [ERR_ASSERTION]: Width must be between $ and 119.
    at globalThis.assert (file:///home/dana_cheng/socratex/node_modules/utilitas/lib/horizon.mjs:15:22)
    at Module.renderBox (file:///home/dana_cheng/socratex/node_modules/utilitas/lib/utilitas.mjs:534:5)
    at initPrimary (file:///home/dana_cheng/socratex/main.mjs:146:30)
    at runFunc (file:///home/dana_cheng/socratex/node_modules/utilitas/lib/callosum.mjs:27:52)
    at Module.init (file:///home/dana_cheng/socratex/node_modules/utilitas/lib/callosum.mjs:121:15)
    at async file:///home/dana_cheng/socratex/main.mjs:118:1 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  status: undefined
}

Node.js v19.9.0

I tried both modern method and classic method. Same errors.

Also I tried to install it with Docker. I got nothing but this:
09350b3ddcbbd137b50681fe7119cb3198005627f8aabf90520b4fe62318374b

I tried to set it up on two Ubuntu VMs. I am stuck with the same error. Not sure what's missing?

**Comment by Leask** [comment]
Sorry, I will fix this issue tomorrow. 🤣

**Comment by Leask** [comment]
Fixed, thank you for submitting this issue. 🙏

**Comment by JJYpeak** [comment]
Thank you so much Leask.

Now I got some progress. But I still didn't get what I expect. The
following is the output when I installed Socratex in Classic mode:

----------------------start of output-------------------------
╭ socratex v2.0.15
────────────────────────────────────────────────────────────────────────────────────────────────────╮
│
                                           │
│ * Token authentication:
                                           │
│   - PAC  :
https://www6.buntzen.xyz/proxy.pac?token=7168b6e6-5b56-3e7d-53e2-f7da931f3930
                            │
│   - WPAD :
https://www6.buntzen.xyz/wpad.dat?token=7168b6e6-5b56-3e7d-53e2-f7da931f3930
                             │
│   - Log  :
https://www6.buntzen.xyz/console?token=7168b6e6-5b56-3e7d-53e2-f7da931f3930
                              │
│
                                           │
│ * Get help:
                                           │
│   - GitHub : https://github.com/Leask/socratex
                                            │
│   - Email  : Leask Wong ***@***.***>
                                            │
│
                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[EVENT 2023-04-23T01:19:18.739Z] Initialized.
[EVENT > CALLOSUM 2023-04-23T01:19:18.740Z] Scheduled.
***@***.*** Secure Web Proxy started at https://www6.buntzen.xyz:443 (IPv6
::).
***@***.*** Secure Web Proxy started at https://www6.buntzen.xyz:443 (IPv6
::).
[CALLOSUM] Successfully launched within 5.44 seconds.
[EVENT > SSL 2023-04-23T01:19:22.708Z] Scheduled.
[EVENT > WEB 2023-04-23T01:19:22.709Z] Scheduled.
[SSL] Challenge HTTP Server started:
{"address":"::","family":"IPv6","port":80}
[WEB 2023-04-23T01:19:22.711Z] Restored 0 session(s), 0 bypass-item(s).
[WEB 2023-04-23T01:19:22.748Z] Saved 0 session(s), 0 bypass-item(s).
[WEB 2023-04-23T01:20:22.810Z] Saved 0 session(s), 0 bypass-item(s).
[WEB 2023-04-23T01:21:22.877Z] Saved 0 session(s), 0 bypass-item(s).
[WEB 2023-04-23T01:22:22.941Z] Saved 0 session(s), 0 bypass-item(s).
-------------------------- end of output---------------------------

I don't see the message about updating certificate. The output is not like
what you post in Github either.

I tried to set up proxy script using the PAC URL shown in the output. But
unfortunately the proxy doesn't work. I tested it in Firefox and got
timedout error like below.
Connection Timedout

Reference #0.3a65edea.8efb2b0e.1682213068


I don't know what I missed?

Thanks again.

Josh

**Comment by Ginhing** [comment]
Hi, I met a similar problem and I think the reason is that [ssl.init()](https://github.com/Leask/utilitas/blob/master/lib/ssl.mjs#L142) does not create cert on the first time.

**Comment by Leask** [comment]
fixed https://github.com/Leask/socratex/issues/11
